# Generated by Django 2.1 on 2019-12-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='read_num',
        ),
    ]
